# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1359019735);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1359019615);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.search.countryCode", "HU");
user_pref("browser.search.region", "HU");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 21);
user_pref("datareporting.sessions.current.startTime", "1474003568850");
user_pref("datareporting.sessions.current.totalTime", 3);
user_pref("datareporting.sessions.currentIndex", 15);
user_pref("datareporting.sessions.previous.0", "{\"s\":1473925007928,\"a\":1,\"t\":20,\"c\":true,\"m\":440,\"fp\":11666,\"sr\":-1}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1473925030896,\"a\":12,\"t\":58,\"c\":true,\"m\":30,\"fp\":1102,\"sr\":-1}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1474003498414,\"a\":1,\"t\":3,\"c\":true,\"m\":12,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1474003508367,\"a\":1,\"t\":3,\"c\":true,\"m\":10,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1474003514234,\"a\":1,\"t\":2,\"c\":true,\"m\":30,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1474003519711,\"a\":1,\"t\":4,\"c\":true,\"m\":11,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1474003563905,\"a\":1,\"t\":2,\"c\":true,\"m\":31,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1473925092753,\"a\":4,\"t\":19,\"c\":true,\"m\":20,\"fp\":1093,\"sr\":-1}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1473926454928,\"a\":5,\"t\":25,\"c\":true,\"m\":20,\"fp\":945,\"sr\":-1}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1474003326585,\"a\":7,\"t\":54,\"c\":true,\"m\":30,\"fp\":14973,\"sr\":-1}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1474003422600,\"a\":0,\"t\":10,\"c\":true,\"m\":30,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1474003436256,\"a\":1,\"t\":4,\"c\":true,\"m\":30,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1474003442198,\"a\":1,\"t\":2,\"c\":true,\"m\":20,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1474003451020,\"a\":1,\"t\":2,\"c\":true,\"m\":15,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1474003455920,\"a\":8,\"t\":38,\"c\":true,\"m\":31,\"fp\":1032,\"sr\":-1}");
user_pref("dom.ipc.plugins.flash.subprocess.crashreporter.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"langpack-hu@thunderbird.mozilla.org\":{\"version\":\"45.2.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-hu@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"45.2.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.2.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.2.0");
user_pref("extensions.lastPlatformVersion", "45.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}\":{\"d\":\"/usr/lib/thunderbird/extensions/{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}\",\"e\":false,\"v\":\"2.6\",\"st\":1469613833000,\"mt\":1262304000000},\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":{\"d\":\"/usr/lib/thunderbird/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}\",\"e\":false,\"v\":\"4.7.2\",\"st\":1469613834000,\"mt\":1262304000000},\"langpack-hu@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-hu@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"45.2.0\",\"st\":1467658634000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"45.2.0\",\"st\":1467658599000},\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1467656294000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.2.0\",\"st\":1467656463000}}}");
user_pref("ldap_2.servers.eds.description", "EDS Address Book Bootstrapper");
user_pref("ldap_2.servers.eds.dirType", 3);
user_pref("ldap_2.servers.eds.filename", "eds.mab");
user_pref("ldap_2.servers.eds.position", 1);
user_pref("ldap_2.servers.eds.uri", "moz-abedsdirectory://");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.preferences.applications.selectedTabIndex", 1);
user_pref("mail.preferences.compose.selectedTabIndex", 2);
user_pref("mail.preferences.display.selectedTabIndex", 0);
user_pref("mail.preferences.security.selectedTabIndex", 0);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.manualMark", true);
user_pref("mail.spam.markAsReadOnSpam", true);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 11);
user_pref("mailnews.database.global.datastore.id", "731e91d2-976b-4266-b8e9-1e8bfb6c8bc");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page.enabled", false);
user_pref("mailnews.start_page_override.mstone", "45.2.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Fontos");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Munka");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Személyes");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Teendők");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Később");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("plugin.importedState", true);
user_pref("signon.importedFromSqlite", true);
user_pref("spellchecker.dictionary", "hu-HU");
user_pref("toolkit.telemetry.cachedClientID", "16ae5016-2c41-4be3-a808-2e8f1a7c3409");
user_pref("toolkit.telemetry.previousBuildID", "20160704153737");
user_pref("toolkit.telemetry.prompted", 2);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
